### ISSUE TITLE
disable github cloning

### ISSUE THREAD

**Issue by unixfox** [bolt-rip/config-pgm#2]
```
[PGM] Cloning github.com/PGMDev/Maps on the default branch... (this may take a while)
```
this thing takes useless time.

**Comment by unixfox** [comment]
Current workaround is to clone an empty repo:
```yml
repositories:
    - uri: "https://github.com/sarcasticadmin/empty-repo"
      path: "/tmp/empty"
```
